_episodes/01-what-is-git.md

The lesson as is jumps right into Git without motivating VC. Tried to give a bit of background and overview on the motivation for Version Control and what the term means.

Explain version control before Git

---

_episodes/02-getting-started.md

- Added question about `git status` to reflect the existence of this content in the section
- Enhanced objectives to answer "The learner will..." and to cover all 3 components of this section
- Clarified takeaways present in key points

Update 02-getting-started questions, objectives, key points

---

_episodes/05-github-pages.md

- Add question to address the content of the section
- Enhance objectives to describe what learners will do in this section
- Clarify key points to summarize the section's critical information

Update 05-github-pages overview

---

_episodes/04-review.md

- Clarify Questions and Key Points to cover what this section actually does
- Enhance objectives to conform to Bloom's Taxonomy and complete the phrase, "The learner will..."

Update 04-review Overview section

---

_episodes/02-getting-started.md

Mainly grammatical changes and added clarity
Please delete the text below before submitting your contribution. 
---
Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.  
Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution …

Updated language, grammatical changes

---

_episodes/03-sharing.md

- Updated questions to match section content, including presence of `git diff` in this section
- Updated objectives to match section content and answer, "The learner will..."
- Updated key points to highlight all essential elements covered in this section

Update 03-sharing overview

---

_episodes/01-what-is-git.md

Updated open-licensed & version control language, added Journal of Open Source Software link as example
Please delete the text below before submitting your contribution. 
---
Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.  
Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process …

Update language used, added JOSS link

---

_episodes/02-getting-started.md
fig/git-staging-area.svg

Using the image from Software Carpentry git lesson, episode 04.

Add image for git staging area in 02-getting-started

---

reference.md

Added GitHub Learning Labs and Desktop to further reading, fixes https://github.com/LibraryCarpentry/lc-git/issues/34

Added GitHub Learning Labs and Desktop to further reading

---

_episodes/05-github-pages.md

Created section for view your site to highlight the "final product" section and increase readability of the page. Edited site url from to match the language in the remainder of the lesson.

Updated visiting GitHub page language to increase readability and make language consistent.

---

_episodes/01-what-is-git.md

I found this in https://github.com/data-lessons/library-git-DEPRECATED/pull/54. Please find the description there.
@sharilaster: Apologies for this almost getting lost due to migrating the repo here. Please have a renewed look at the changes. Do they still reflect what you suggested back then?

Shift emphasis from title to work

---

index.md

Currently links to setup.html on main domain.
Please delete this line and the text below before submitting your contribution.
---
Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.  
Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a …

Fix link to be relative to index within repo

---

index.md

Update point of view in intro

---

reference.md

fix link to pymarc

---

reference.md

Remove the term "basic" in the reference page

Remove "basic" in reference page

---

_episodes/03-sharing.md

At end of Pushing changes section, I revised this sentence:
If we are very forgetful and have already forgotten what we change**s we have made**, git log allows us to look at what we have been doing with our git repository (in reverse chronological order, with the very latest changes first).
to remove the bold and just have a d.

English syntax error

---

episodes/01-what-is-git.md

The start of the "What is Git/GitHub" states that "modern version control systems can be used to track changes in any type of file" but later says "Since Word documents contain special formatting, Git unfortunately cannot version control those, nor can it version control PDFs, though both file types can be stored in Git repositories."
This PR changes "any type" to "most types" to avoid contradicting later information.

"all types" --> "most types"

---

CONTRIBUTING.md

testing whether that will queue a re-build of the page.

Made a bad change to CONTRIBUTING.md

---

CONTRIBUTING.md

Reverse bad change to CONTRIBUTING.md

---

README.md

This pull request updates the list of Maintainers for this lesson to include myself and @srerickson.
@maneesha , should you be listed here somewhere?

Update list of Maintainers
