_episodes/01-what-is-git.md
- Enhanced the objectives for 01-what-is-git by applying Bloom's Taxonomy so that they would answer the question, "The learner will..."
- Added a key point on version control
- Clarified second point on "Why Git for Librarians?"
=> Updates to Objectives 01

_episodes/02-getting-started.md
Fixes issue https://github.com/LibraryCarpentry/lc-git/issues/19 to added a clearer heading
=> Change to staging area note heading

reference.md
kcl/ddh did not seem to have a clear replacement, see https://github.com/kcl/ & https://github.com/search?q=ddh+digital+humanities
=> Repair or remove broken links

setup.md
I don't think `edit` comes installed by default on Mac. (It's not on mine...)
On the other hand, `nano` should be there by default. It's also the [recommended text editor](https://github.com/carpentries/workshop-template/blob/gh-pages/index.md#text-editor) for Software Carpentry.
If you all prefer `edit`, perhaps we can include instructions on how to install `edit` if it's not available.
=> change `edit` to `nano`

_extras/guide.md
- Included links in guide instead of referencing links.md
- Updated handout reference link
- Removed "Librarians love handouts"
=> Fix guide links

_episodes/01-what-is-git.md, _episodes/05-github-pages.md, index.md, reference.md
This cleans up a few occurrences that didn't have the official capitalization.
=> Make GitHub references consistent with official capitalization.

reference.md
Minor rewording & link updates. GitHub Desktop [no longer includes the tutorial](https://github.com/desktop/desktop/issues/1933#issuecomment-307337892).
=> Update GitHub tutorial links

_episodes/02-getting-started.md
After `git status` the message reads:
On branch master
No commits yet
nothing to commit (create/copy files and use "git add" to track)
Change 'Initial commit' to 'No commits yet' to reflect the correct status message
=> Change initial commit to no commits yet

_extras/guide.md
https://librarycarpentry.org/lc-git/reference/ was not working
Corrected to https://librarycarpentry.org/lc-git/reference.html
=> Correct reference link

index.md
This section is redundant since this is covered in Extras>Discussion and Contributing. Removing per https://github.com/LibraryCarpentry/lc-git/pull/53.
=> Remove ways to contribute

reference.md
Make the cheat sheet links active, fix broken link.
Rework the basic git command descriptions, tried to clarify (esp. push
and pull) and match the style of the prior sections.
=> Fix cheat sheet links, git command descriptions

_episodes/05-github-pages.md
In Library carpentry Introduction to Git lesson 5 - GitHub Pages, the contributing to page owned by someone else, figuring out how to make a PR to owner could be a bit difficult. By following the instruction from the lesson, we are able to make a PR in our own repo to master/other branches instead of making to the original repo of the owner. So when the owner tries to approve the PR, they don't see any PR requested.
Instead, I think, we can suggest the learners to commit the new change and then go to the repo and click `New Pull Request` button which will take us to a web page from where we can make a PR to owner's repo.
Also, the spelling of "Practice" is wrongly spelled as "practise" in Challenge: Contributing to a page owned by someone else (slightly easier way) section
=> Fixing PR to Repo owned by someone else.

_config.yml
Excellent @dcmcand  and @libcce!  Thanks for the info. This PR adds the lifecycle info to `_config.yml` and sets to **stable**.  This is a relatively new setting in the config. We should also change the status on here: https://librarycarpentry.org/lessons/ to let folks know it is stable.  This closes #84.
=> adding lifecycle info to _config

_episodes/03-sharing.md
This PR addresses https://github.com/LibraryCarpentry/lc-git/issues/77. 
The `upstream` word needs to be explained as it is not clear "where" it comes from, to new users of git.
Please delete this line and the text below before submitting your contribution.
---
Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.  
Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to …
=> Explain usage of the **upstream** keyword

_episodes/02-getting-started.md, _episodes/03-sharing.md, _episodes/05-github-pages.md
Just taught this lesson and thought I would submit this right away! This replaces all text instances where the word "master" needed to be changed to "main" to reflect new git standards. I did not change the image in episode 2 (described in issue #99 ) as I was not sure what the best solution was. Happy to work on that too but thought it might best be handled separately.
=> Change text of three episodes to replace 'master' with 'main'

README.md, _episodes/02-getting-started.md
Per our discussion on the Carpentries Slack (channel: libraries). Chuck informed me that he is not a current maintainer. I checked the README.md and saw he was still listed as a current maintainer. With his permission, I asked if I could move his name from "Current Maintainer" to "Past Maintainer" and he said please do.
=> Updated List of Current and Past Maintainers

setup.md
Addresses issue https://github.com/LibraryCarpentry/lc-git/issues/99
Git now includes a global setting `init.defaultBranch` for setting "main" as the default branch name for new local repositories. [More Info.](https://github.blog/2020-07-27-highlights-from-git-2-28/#introducing-init-defaultbranch).
See also: https://github.com/github/renaming
This adds an additional line of code to the setup page as well as an explanation of the code in the following paragraph. This issue caused some confusion while teaching the lesson to beginners. Maintainers may want to consider going into more detail if they think it's appropriate.
=> modify setup page with new init.defaultBranch main instructions

_episodes/02-getting-started.md
Closing issue #110 with revision from @michellehudson (Thanks!)
=> Closing issue #110 with revision from @michellehudson (Thanks!) 

_episodes/05-github-pages.md
Fixes #128 by replacing the broken link to the Thinkful tutorial with a more up-to-date resource on forking, cloning, and pull requests. Hopefully this guide from GitHub is a safer bet in terms of long-term maintenance and availability.
=> link to GitHub guide on contributing to a project

_episodes/02-getting-started.md
The text about the GitHub email address was duplicated.
=> Remove duplicated text about email address

_episodes/02-getting-started.md, _extras/guide.md
This PR involves a few different changes. 
One part fixes #108. I've made a very small callout inside episode 2 to discuss the wide world of text editors and why we recommend nano for this lesson. 
For reviewers, I welcome your suggestions about whether the callout should be moved to the bottom of the episode or stay where it is. 
Also, I think that adding something about text editors to the Instructor Notes is a good idea, but I will do that separately. 
This PR also involves a very small edit to the Instructor's Notes about a known problem with Windows and Open SSH. I confess that I don't fully understand the problem yet, so this is more of an early warning to instructors. I will try to address it more fully in a subsequent PR, but for now, at least it's the beginning of a warning and …
=> 108 text editor callout

_episodes/05-github-pages.md
gh-pages branch is not required any more. A previous reference has been removed by PR https://github.com/LibraryCarpentry/lc-git/pull/103, however there remained a leftover. This change removes that.
=> Remove reference to gh-pages branch

_episodes/02-getting-started.md
This will help me perform the transition for this lesson by removing an unneeded tag (see https://github.com/carpentries/lesson-transition/issues/63)
=> remove stray "source" tag

_episodes/02-getting-started.md
I noticed the paragraph about email addresses was written in roundabout language, so I rewrote the paragraph to be more simple and direct.
=> additional prose improvements 

_episodes/03-sharing.md
The teaching time for this episode had not been updated since we added the SSH setup portion in 2021. The episode takes substantially longer now. I participated in a Library Carpentry workshop this week, and I kept track of the time required for the episode, and I have updated it to reflect a more accurate time.
=> updated time of lesson based on teaching experience

.zenodo.json
Updates the `.zenodo.json` file containing metadata for releasing the lesson to Zenodo before the infrastructure transition.
=> update .zenodo.json file for lesson release

learners/setup.md
_If this pull request addresses an open issue on the repository, please add 'Closes #NN' below, where NN is the issue number._
Fixes #145 
_Please briefly summarise the changes made in the pull request, and the reason(s) for making these changes._
This adds guidance for learners about setting up multi-factor authentication. It outsources most of the configuration instructions to GitHub themselves, as the interface and process may change relatively often.
I also replaced the previous instructions for installing Git with links to the Git section of [the Installation Instructions page of the workshop website template](https://carpentries.github.io/workshop-template/install_instructions), as these are more comprehensive and will be updated if and when the steps change to set up command line …
=> update GitHub account setup instructions

CONTRIBUTING.md
_If this pull request addresses an open issue on the repository, please add 'Closes #NN' below, where NN is the issue number._
Fixes #154 
_Please briefly summarise the changes made in the pull request, and the reason(s) for making these changes._
It seems this link was misconfigured in #147, so the link in `CONTRIBUTING.md` was pointing to example.com instead of the lesson repository. This PR corrects the URL for the link.
=> fix link URL for issue listing

episodes/02-getting-started.md
Hi, just taught this today and wondered why Windows is isolated with notepad, since nano was used in the Unix Shell lesson. So I pulled the line mentioning notepad, edited the statement to be Win, Appl and LInux, and removed the box of code.
It's a bit odd because we don't return to a text editor through the command line.  I like the way the learners can see the same effect from the gui interface of editing a file to push and commit.  So maybe there's another line left over in a different part of the lesson to also update about notepad and text editing.
@chennesy I'll add Cody, as we co-taught.
=> Remove Notepad for Windows

README.md
Regular maintenance of information to reflect accurately who is an active maintainer of this lesson. We must have forgotten to edit this a year or more ago when the maintainers changed.
=> Updated list of maintainers for this lesson on the readme

episodes/02-getting-started.md
Remove language where terms are defined as "simply" something.
=> remove dismissive language

learners/reference.md
This pull requests fixes two issues with the `learners/reference.md` page:
- The page title should not be "FIXME". "Reference" seems reasonable as it contains both a summary of key commands and links to further reading.
- The Glossary section has no content, so the heading should be removed. To be clear, this is not a comment on the usefulness or otherwise of having a glossary; it only reflects the fact that we do not have a glossary at the moment.
=> Tidy up reference page

learners/reference.md
Remove extra trailing 'c' in link https://gitlab.com/pymarc/pymarcc
=> Update reference.md to fix broken link

learners/reference.md
Hey all,
This PR addresses https://github.com/LibraryCarpentry/lc-git/issues/168
The existing link did not work for me until I went through the newly proposed link first. From there you can either view the book in dynamic form as it was linked to before or use another link to get a pdf. This has been described in the issue linked here above. 
Kind regards,
Timo
=> Update reference to opening science book

episodes/02-getting-started.md, episodes/05-github-pages.md, episodes/fig/git-branch.svg, episodes/fig/git-branches.svg
These changes provide the explanation of branches that is promised but not delivered in the lesson.
In order to keep the cognitive load light, I've split the explanation into two parts:
- In episode 2, following the use of `git status`, we explain branches as labelled sequences of commits. This is all we need for episodes 2-4. 
- In episode 5, following the first pull request challenge, we explain what just happened in terms of branching and merging.
Each of these is illustrated with a diagram. The first one is there primarily to make the second one seem more familiar.
- In common with how the Git Book does it, the arrows between commits point backwards in time. I've used triangular arrow heads to evoke how UML shows class inheritance: each commit "inherits" the last one then changes it a …
=> Add callouts explaining branches
